### ISSUE TITLE
Add role mysqldump

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-backup#2]
For very basic setups we need automated configuration of mysql dumps

**Comment by widhalmt** [comment]
For starters we can provide a script via template that's run per cron. (Don't forget to create target directories etc.)

Please add a check via molecule that runs `verify.yml` to prove that the backup is actually working. e.g. use `prepare.yml` to set up a database (maybe with https://github.com/geerlingguy/ansible-role-mysql ), than run a first backup, drop the database and restore the backup. Of course a similar meaningful check would be just as welcome.

**Comment by afeefghannam89** [comment]
this is done in the following [MR 15](https://github.com/NETWAYS/ansible-collection-backup/pull/15)
